2012/04/25 20:05:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "auth".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('auth')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/auth
---
2012/04/25 20:06:23 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Could not find oauth service' in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php:41
Stack trace:
#0 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionOauth()
#1 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#2 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#3 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('oauth')
#5 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/oauth')
#6 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#7 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/oauth
---
2012/04/25 20:06:54 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Could not find oauth service' in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php:41
Stack trace:
#0 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionOauth()
#1 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#2 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#3 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('oauth')
#5 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/oauth/g...')
#6 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#7 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/oauth/google
---
2012/04/25 20:07:10 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Could not find oauth service' in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php:42
Stack trace:
#0 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionOauth()
#1 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#2 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#3 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('oauth')
#5 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/oauth/g...')
#6 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#7 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/oauth/google
---
2012/04/25 20:07:20 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Could not find oauth service' in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php:41
Stack trace:
#0 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionOauth()
#1 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#2 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#3 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('oauth')
#5 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/oauth/g...')
#6 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#7 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/oauth/google
---
2012/04/25 20:07:33 [error] [exception.EAuthException] exception 'EAuthException' with message 'Undefined service name: .' in /var/www/yii-cp/as2/protected/extensions/eauth/EAuth.php:82
Stack trace:
#0 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(14): EAuth->getIdentity('')
#1 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionOauth()
#2 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#3 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#4 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('oauth')
#6 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/oauth/g...')
#7 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/oauth/google
---
2012/04/25 20:08:15 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Could not find oauth service' in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php:42
Stack trace:
#0 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionOauth()
#1 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#2 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#3 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('oauth')
#5 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/oauth/g...')
#6 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#7 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/oauth/google
---
2012/04/25 20:10:28 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Could not find oauth service' in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php:42
Stack trace:
#0 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionOauth()
#1 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#2 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#3 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('oauth')
#5 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/oauth')
#6 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#7 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/oauth
---
2012/04/25 20:10:31 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Could not find oauth service' in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php:42
Stack trace:
#0 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionOauth()
#1 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#2 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#3 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('oauth')
#5 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/oauth')
#6 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#7 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/oauth
---
2012/04/25 20:10:33 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Could not find oauth service' in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php:42
Stack trace:
#0 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionOauth()
#1 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#2 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#3 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('oauth')
#5 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/oauth')
#6 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#7 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/oauth
---
2012/04/25 20:10:36 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Could not find oauth service' in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php:42
Stack trace:
#0 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionOauth()
#1 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#2 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#3 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('oauth')
#5 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/oauth')
#6 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#7 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/oauth
---
2012/04/25 20:10:38 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Could not find oauth service' in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php:42
Stack trace:
#0 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionOauth()
#1 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#2 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#3 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('oauth')
#5 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/oauth')
#6 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#7 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/oauth
---
2012/04/25 20:11:48 [error] [php] include(LinkedinOAuthService.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (/var/www/yii-cp/framework/YiiBase.php:418)
Stack trace:
#0 /var/www/yii-cp/as2/protected/extensions/eauth/EAuth.php(93): spl_autoload_call()
#1 /var/www/yii-cp/as2/protected/extensions/eauth/EAuth.php(37): EAuth->getIdentity()
#2 /var/www/yii-cp/as2/protected/extensions/eauth/EAuthWidget.php(51): EAuth->getServices()
#3 /var/www/yii-cp/framework/web/CBaseController.php(148): EAuthWidget->init()
#4 /var/www/yii-cp/framework/web/CBaseController.php(173): SiteController->createWidget()
#5 /var/www/yii-cp/as2/protected/modules/as/views/site/login.php(12): SiteController->widget()
#6 /var/www/yii-cp/framework/web/CBaseController.php(127): require()
#7 /var/www/yii-cp/framework/web/CBaseController.php(96): SiteController->renderInternal()
#8 /var/www/yii-cp/framework/web/CController.php(870): SiteController->renderFile()
#9 /var/www/yii-cp/framework/web/CController.php(783): SiteController->renderPartial()
#10 /var/www/yii-cp/as2/protected/modules/as/controllers/SiteController.php(92): SiteController->render()
#11 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#12 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams()
#13 /var/www/yii-cp/framework/web/CController.php(287): SiteController->runAction()
#14 /var/www/yii-cp/framework/web/CController.php(266): SiteController->runActionWithFilters()
#15 /var/www/yii-cp/framework/web/CWebApplication.php(276): SiteController->run()
#16 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController()
#17 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#18 /var/www/yii-cp/as2/index.php(13): CWebApplication->run()
REQUEST_URI=/yii-cp/as2/index.php/as/site/login
in /var/www/yii-cp/as2/protected/extensions/eauth/EAuth.php (93)
in /var/www/yii-cp/as2/protected/extensions/eauth/EAuth.php (37)
in /var/www/yii-cp/as2/protected/extensions/eauth/EAuthWidget.php (51)
2012/04/25 20:15:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "login".' in /var/www/yii-cp/framework/web/CController.php:484
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(271): CController->missingAction('login')
#1 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('login')
#2 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/login')
#3 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/login
---
2012/04/25 20:15:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "login".' in /var/www/yii-cp/framework/web/CController.php:484
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(271): CController->missingAction('login')
#1 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('login')
#2 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/login')
#3 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/login
---
2012/04/25 20:16:17 [error] [exception.CException] exception 'CException' with message 'AuthController cannot find the requested view "login".' in /var/www/yii-cp/framework/web/CController.php:879
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(783): CController->renderPartial('login', Array, true)
#1 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(61): CController->render('login', Array)
#2 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(7): AuthController->actionAuth()
#3 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionIndex()
#4 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#5 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#6 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('')
#8 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth')
#9 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth
---
2012/04/25 20:16:36 [error] [exception.CException] exception 'CException' with message 'AuthController cannot find the requested view "site/login".' in /var/www/yii-cp/framework/web/CController.php:879
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(783): CController->renderPartial('site/login', Array, true)
#1 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(61): CController->render('site/login', Array)
#2 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(7): AuthController->actionAuth()
#3 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionIndex()
#4 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#5 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#6 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('')
#8 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth')
#9 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth
---
2012/04/25 20:16:55 [error] [exception.CException] exception 'CException' with message 'AuthController cannot find the requested view "site.login".' in /var/www/yii-cp/framework/web/CController.php:879
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(783): CController->renderPartial('site.login', Array, true)
#1 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(61): CController->render('site.login', Array)
#2 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(7): AuthController->actionAuth()
#3 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionIndex()
#4 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#5 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#6 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('')
#8 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth')
#9 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth
---
2012/04/25 20:26:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "as/as/auth/auth/service/google_oauth".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/as/auth/auth...')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/as/auth/auth/service/google_oauth?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle_oauth&js
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth
---
2012/04/25 20:26:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "as/aut".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/aut')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/aut
---
2012/04/25 20:26:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "as/as/auth/login".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/as/auth/logi...')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/as/auth/login
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth
---
2012/04/25 20:26:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "as/as/auth/login".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/as/auth/logi...')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/as/auth/login
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth
---
2012/04/25 22:01:27 [error] [php] include(GoogleOAuthService.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (/var/www/yii-cp/framework/YiiBase.php:418)
Stack trace:
#0 /var/www/yii-cp/as2/protected/extensions/eauth/EAuth.php(93): spl_autoload_call()
#1 /var/www/yii-cp/as2/protected/extensions/eauth/EAuth.php(37): EAuth->getIdentity()
#2 /var/www/yii-cp/as2/protected/extensions/eauth/EAuthWidget.php(51): EAuth->getServices()
#3 /var/www/yii-cp/framework/web/CBaseController.php(148): EAuthWidget->init()
#4 /var/www/yii-cp/framework/web/CBaseController.php(173): AuthController->createWidget()
#5 /var/www/yii-cp/as2/protected/modules/as/views/site/login.php(12): AuthController->widget()
#6 /var/www/yii-cp/framework/web/CBaseController.php(127): require()
#7 /var/www/yii-cp/framework/web/CBaseController.php(96): AuthController->renderInternal()
#8 /var/www/yii-cp/framework/web/CController.php(870): AuthController->renderFile()
#9 /var/www/yii-cp/framework/web/CController.php(783): AuthController->renderPartial()
#10 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(61): AuthController->render()
#11 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(7): AuthController->actionAuth()
#12 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionIndex()
#13 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams()
#14 /var/www/yii-cp/framework/web/CController.php(287): AuthController->runAction()
#15 /var/www/yii-cp/framework/web/CController.php(266): AuthController->runActionWithFilters()
#16 /var/www/yii-cp/framework/web/CWebApplication.php(276): AuthController->run()
#17 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController()
#18 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#19 /var/www/yii-cp/as2/index.php(13): CWebApplication->run()
REQUEST_URI=/yii-cp/as2/index.php/as/auth
in /var/www/yii-cp/as2/protected/extensions/eauth/EAuth.php (93)
in /var/www/yii-cp/as2/protected/extensions/eauth/EAuth.php (37)
in /var/www/yii-cp/as2/protected/extensions/eauth/EAuthWidget.php (51)
2012/04/25 22:07:08 [error] [php] include(GoogleOAuthService.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (/var/www/yii-cp/framework/YiiBase.php:418)
Stack trace:
#0 /var/www/yii-cp/as2/protected/extensions/eauth/EAuth.php(93): spl_autoload_call()
#1 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(21): EAuth->getIdentity()
#2 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionAuth()
#3 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams()
#4 /var/www/yii-cp/framework/web/CController.php(287): AuthController->runAction()
#5 /var/www/yii-cp/framework/web/CController.php(266): AuthController->runActionWithFilters()
#6 /var/www/yii-cp/framework/web/CWebApplication.php(276): AuthController->run()
#7 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController()
#8 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#9 /var/www/yii-cp/as2/index.php(13): CWebApplication->run()
REQUEST_URI=/yii-cp/as2/index.php/as/auth/auth/service/google_oauth?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle_oauth&js
in /var/www/yii-cp/as2/protected/extensions/eauth/EAuth.php (93)
in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php (21)
in /var/www/yii-cp/as2/index.php (13)
2012/04/25 22:07:16 [error] [php] include(GoogleOAuthService.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (/var/www/yii-cp/framework/YiiBase.php:418)
Stack trace:
#0 /var/www/yii-cp/as2/protected/extensions/eauth/EAuth.php(93): spl_autoload_call()
#1 /var/www/yii-cp/as2/protected/extensions/eauth/EAuth.php(37): EAuth->getIdentity()
#2 /var/www/yii-cp/as2/protected/extensions/eauth/EAuthWidget.php(51): EAuth->getServices()
#3 /var/www/yii-cp/framework/web/CBaseController.php(148): EAuthWidget->init()
#4 /var/www/yii-cp/framework/web/CBaseController.php(173): AuthController->createWidget()
#5 /var/www/yii-cp/as2/protected/modules/as/views/site/login.php(12): AuthController->widget()
#6 /var/www/yii-cp/framework/web/CBaseController.php(127): require()
#7 /var/www/yii-cp/framework/web/CBaseController.php(96): AuthController->renderInternal()
#8 /var/www/yii-cp/framework/web/CController.php(870): AuthController->renderFile()
#9 /var/www/yii-cp/framework/web/CController.php(783): AuthController->renderPartial()
#10 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(68): AuthController->render()
#11 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(7): AuthController->actionAuth()
#12 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionIndex()
#13 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams()
#14 /var/www/yii-cp/framework/web/CController.php(287): AuthController->runAction()
#15 /var/www/yii-cp/framework/web/CController.php(266): AuthController->runActionWithFilters()
#16 /var/www/yii-cp/framework/web/CWebApplication.php(276): AuthController->run()
#17 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController()
#18 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#19 /var/www/yii-cp/as2/index.php(13): CWebApplication->run()
REQUEST_URI=/yii-cp/as2/index.php/as/auth
in /var/www/yii-cp/as2/protected/extensions/eauth/EAuth.php (93)
in /var/www/yii-cp/as2/protected/extensions/eauth/EAuth.php (37)
in /var/www/yii-cp/as2/protected/extensions/eauth/EAuthWidget.php (51)
2012/04/25 22:09:20 [error] [exception.EAuthException] exception 'EAuthException' with message 'Unable to complete the authentication because the required data was not received.' in /var/www/yii-cp/as2/protected/extensions/eauth/EOpenIDService.php:77
Stack trace:
#0 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(25): EOpenIDService->authenticate()
#1 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionAuth()
#2 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#3 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#4 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('auth')
#6 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/auth/se...')
#7 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-25T20%3A07%3A43ZeW9DQ3ie1wQvtw&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9VoNvecNc7hxl7JhHaNOu5Y-9kiAzFYc2cziVg9ytJxJyfgIxpr&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=ytEr2ONDVkjbAONDrAgxxK%2F8JtM%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth
---
2012/04/25 22:16:51 [error] [exception.EAuthException] exception 'EAuthException' with message 'Unable to complete the authentication because the required data was not received.' in /var/www/yii-cp/as2/protected/extensions/eauth/EOpenIDService.php:77
Stack trace:
#0 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(25): EOpenIDService->authenticate()
#1 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionAuth()
#2 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#3 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#4 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('auth')
#6 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/auth/se...')
#7 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-25T20%3A16%3A24ZqCoPBbo5tZznWQ&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9U6bJtPSZ3J-WkLNeDdLy4ncoqxiKW_wfgPJIG46gLIAIVc-l7E&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=AoLnkxaYQW5RD%2BzGESN2Gu2fDDY%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth
---
2012/04/25 22:17:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "as/aut".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/aut')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/aut
---
2012/04/25 22:18:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "as/as/auth/success".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/as/auth/succ...')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/as/auth/success
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-25T20%3A18%3A02ZnV-5uM09FBlMQw&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9UXEgVqDKmIWuRPugqfqqXrUifaLMNxBqZpkjVKN0q7coK625GR&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=g1fr4rI%2ByEfYLoiJPrN4eR3MPLE%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
---
2012/04/25 22:18:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "success".' in /var/www/yii-cp/framework/web/CController.php:484
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(271): CController->missingAction('success')
#1 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('success')
#2 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/success')
#3 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/success
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-25T20%3A18%3A15ZlGSmao4UVFn-Vw&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9XDrMVcfli49q5BjH6hL9ewc9Y3uB_66xNu9tKXxQ3--t0NNst1&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=d0oMGwL7Ia4%2Fl1MKqKwWaQsONlM%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
---
2012/04/25 22:25:59 [error] [exception.EAuthException] exception 'EAuthException' with message 'Unable to complete the authentication because the required data was not received.' in /var/www/yii-cp/as2/protected/extensions/eauth/EOpenIDService.php:77
Stack trace:
#0 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(25): EOpenIDService->authenticate()
#1 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionAuth()
#2 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#3 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#4 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('auth')
#6 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/auth/se...')
#7 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-25T20%3A24%3A42Z-l8IfMIEPeQoWg&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9VTpn9j4zya_RNTbB-vhO3c-7ZqHsA1WqukVTmPbM8VfrKM51w3&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=JrTw4suIj2OyZ1AOWlV2vjKFfdA%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth
---
2012/04/26 07:24:52 [error] [exception.CException] exception 'CException' with message 'EAuthUserIdentity and its behaviors do not have a method or closure named "getAttribute".' in /var/www/yii-cp/framework/base/CComponent.php:266
Stack trace:
#0 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(33): CComponent->__call('getAttribute', Array)
#1 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(33): EAuthUserIdentity->getAttribute('name')
#2 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionAuth()
#3 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#4 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#5 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('auth')
#7 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/auth/se...')
#8 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#9 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T05%3A24%3A50ZK74gQfcTAcLedw&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9XCPDl-qf1F99BE6JRYNT2yUVcbxVm87TLTw3buekns3A6LMnf5&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=KO3Ws2jUhhT8L%2F3BvG1YEtD2pPE%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth
---
2012/04/26 07:25:33 [error] [exception.CException] exception 'CException' with message 'Property "User.name" is not defined.' in /var/www/yii-cp/framework/base/CComponent.php:174
Stack trace:
#0 /var/www/yii-cp/framework/db/ar/CActiveRecord.php(160): CComponent->__set('name', 'b.')
#1 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(33): CActiveRecord->__set('name', 'b.')
#2 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionAuth()
#3 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#4 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#5 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('auth')
#7 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/auth/se...')
#8 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#9 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T05%3A25%3A32ZZ0thLLAy993OCg&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9WmuAR17S_gmoK9JbINeQ4iDdQAoBjx0LrlBFQW96E16TWMvgz_&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=wHBx3TfWi4Oe84pLUO4phyFqMeg%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth
---
2012/04/26 07:26:01 [error] [exception.CException] exception 'CException' with message 'Property "User.hashingMethod" is not defined.' in /var/www/yii-cp/framework/base/CComponent.php:174
Stack trace:
#0 /var/www/yii-cp/framework/db/ar/CActiveRecord.php(160): CComponent->__set('hashingMethod', 'plain')
#1 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(36): CActiveRecord->__set('hashingMethod', 'plain')
#2 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionAuth()
#3 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#4 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#5 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('auth')
#7 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/auth/se...')
#8 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#9 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T05%3A26%3A00Z5L3DUatBqWlxNw&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9VSw88C6zgQ75yt6JcMng9nKDpf3H1uqptJFTjVZy4rW_7dGa39&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=Yh81nUPqreivuMNO4pwDzB375HA%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth
---
2012/04/26 07:26:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "success".' in /var/www/yii-cp/framework/web/CController.php:484
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(271): CController->missingAction('success')
#1 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('success')
#2 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/success')
#3 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/success
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T05%3A26%3A36ZDagctCNlWada0g&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9Uq8pcQYEi_Ev-zpE3EkEpCEZrzK902mKDu-Ln0ZijWko0YMbeh&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=BKDbQCEMZn%2FT5qyBFBUdZRnH4R4%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
---
2012/04/26 07:31:12 [error] [php] Undefined variable: authidentity (/var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php:45)
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(287): AuthController->runAction()
#1 /var/www/yii-cp/framework/web/CController.php(266): AuthController->runActionWithFilters()
#2 /var/www/yii-cp/framework/web/CWebApplication.php(276): AuthController->run()
#3 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController()
#4 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#5 /var/www/yii-cp/as2/index.php(13): CWebApplication->run()
REQUEST_URI=/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T05%3A31%3A11ZznJ83nRJ_0sBJw&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9WFfZs36_V4Iy4mDCfe02WbAhFPIFrybBKkilMvvG4zCBGubf55&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=IwxVzsmiwV8fx%2FDAPEEGU8zOSik%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php (45)
in /var/www/yii-cp/as2/index.php (13)
2012/04/26 07:31:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "success".' in /var/www/yii-cp/framework/web/CController.php:484
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(271): CController->missingAction('success')
#1 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('success')
#2 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/success')
#3 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/success
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T05%3A31%3A39ZggQjX_NQflnFCA&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9VSuUh5kJ1RZOtdMAWPeDDElRnPYZluSB6KHP3Rh3kIG2PsbcZu&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=iK%2BgpUPVZ%2BDAMyaZseGbSqWnKGA%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
---
2012/04/26 07:33:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "success".' in /var/www/yii-cp/framework/web/CController.php:484
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(271): CController->missingAction('success')
#1 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('success')
#2 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/success')
#3 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/success
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T05%3A33%3A43ZhVmCqewf4-xDOw&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9WYzuVstooA4bFeNSPISXb2wh177BdaXa7YT2TDhBBadth5jnLb&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=gw1Mv6c%2FTjF0Et%2BgKEg6LJQFWCA%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
---
2012/04/26 07:51:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "success".' in /var/www/yii-cp/framework/web/CController.php:484
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(271): CController->missingAction('success')
#1 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('success')
#2 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/success')
#3 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/success
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T05%3A33%3A43ZhVmCqewf4-xDOw&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9WYzuVstooA4bFeNSPISXb2wh177BdaXa7YT2TDhBBadth5jnLb&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=gw1Mv6c%2FTjF0Et%2BgKEg6LJQFWCA%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
---
2012/04/26 07:51:21 [error] [php] Undefined variable: externaluser (/var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php:34)
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(287): AuthController->runAction()
#1 /var/www/yii-cp/framework/web/CController.php(266): AuthController->runActionWithFilters()
#2 /var/www/yii-cp/framework/web/CWebApplication.php(276): AuthController->run()
#3 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController()
#4 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#5 /var/www/yii-cp/as2/index.php(13): CWebApplication->run()
REQUEST_URI=/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T05%3A51%3A19ZJ-K2MIy0dJHgtw&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9UsgaT862jFPSCVIDkG-BrhgbN3GCmwhPXhYhZg1jztzqaFO6pZ&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=SZtRozkyzFl%2FkIldSFi8MDmkx7Y%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php (34)
in /var/www/yii-cp/as2/index.php (13)
2012/04/26 07:51:32 [error] [exception.EAuthException] exception 'EAuthException' with message 'Unable to complete the authentication because the required data was not received.' in /var/www/yii-cp/as2/protected/extensions/eauth/EOpenIDService.php:77
Stack trace:
#0 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(25): EOpenIDService->authenticate()
#1 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionAuth()
#2 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#3 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#4 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('auth')
#6 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/auth/se...')
#7 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T05%3A51%3A19ZJ-K2MIy0dJHgtw&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9UsgaT862jFPSCVIDkG-BrhgbN3GCmwhPXhYhZg1jztzqaFO6pZ&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=SZtRozkyzFl%2FkIldSFi8MDmkx7Y%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth
---
2012/04/26 07:51:41 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'external_user_id'. The SQL statement executed was: INSERT INTO `external_user` (`user_id`, `oauth_provider_id`, `key`) VALUES (:yp0, :yp1, :yp2).
in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php (66)
in /var/www/yii-cp/as2/index.php (13)
2012/04/26 07:51:41 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'external_user_id'. The SQL statement executed was: INSERT INTO `external_user` (`user_id`, `oauth_provider_id`, `key`) VALUES (:yp0, :yp1, :yp2)' in /var/www/yii-cp/framework/db/CDbCommand.php:354
Stack trace:
#0 /var/www/yii-cp/framework/db/ar/CActiveRecord.php(1014): CDbCommand->execute()
#1 /var/www/yii-cp/framework/db/ar/CActiveRecord.php(787): CActiveRecord->insert(NULL)
#2 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(66): CActiveRecord->save(false)
#3 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionAuth()
#4 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#5 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#6 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('auth')
#8 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/auth/se...')
#9 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T05%3A51%3A38ZwFKthQPgOIxqeQ&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9VroAboxp637H82cXcSPQrtr3OMi2efKLtbQSKBK1rijEmQXiwU&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=r%2Fjwwk0NXGi9n%2BhEuX6ZDKB6tuE%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth
---
2012/04/26 07:52:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "success".' in /var/www/yii-cp/framework/web/CController.php:484
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(271): CController->missingAction('success')
#1 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('success')
#2 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/success')
#3 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/success
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T05%3A52%3A25ZNfFkOBXQo2ef-w&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9W3AqgHufjtcLdS0wFHKLkVJWmoHxqtbPycHsylYX4MJOmjvlfq&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=u3cq2AQeSWdeSIS8f8CbhSXob7Y%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
---
2012/04/26 07:52:32 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'external_user_id'. The SQL statement executed was: INSERT INTO `external_user` (`user_id`, `oauth_provider_id`, `key`) VALUES (:yp0, :yp1, :yp2).
in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php (66)
in /var/www/yii-cp/as2/index.php (13)
2012/04/26 07:52:32 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'external_user_id'. The SQL statement executed was: INSERT INTO `external_user` (`user_id`, `oauth_provider_id`, `key`) VALUES (:yp0, :yp1, :yp2)' in /var/www/yii-cp/framework/db/CDbCommand.php:354
Stack trace:
#0 /var/www/yii-cp/framework/db/ar/CActiveRecord.php(1014): CDbCommand->execute()
#1 /var/www/yii-cp/framework/db/ar/CActiveRecord.php(787): CActiveRecord->insert(NULL)
#2 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(66): CActiveRecord->save(false)
#3 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionAuth()
#4 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#5 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#6 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('auth')
#8 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/auth/se...')
#9 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T05%3A52%3A30Z1DNVW-4hVa-PcA&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9XmPzNcLBRRAl0bH6nKGCZYXmdezwsjgDAG1LcQ67aee1tBlLcJ&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=FzbaR1XVavg71ulnuwW1g4eOM3Y%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth
---
2012/04/26 07:54:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "success".' in /var/www/yii-cp/framework/web/CController.php:484
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(271): CController->missingAction('success')
#1 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('success')
#2 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/success')
#3 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/success
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T05%3A54%3A52ZhiklyvhEcBZ_6A&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9V_9Z0crWgw1AINbgfKdO-4hasmsPkZbWAop4a98LWNur4Uibk9&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=pixqRcXuSLjQwWo2C6C%2FKTxhqzg%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
---
2012/04/26 08:04:14 [error] [php] Undefined variable: identity (/var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php:29)
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(287): AuthController->runAction()
#1 /var/www/yii-cp/framework/web/CController.php(266): AuthController->runActionWithFilters()
#2 /var/www/yii-cp/framework/web/CWebApplication.php(276): AuthController->run()
#3 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController()
#4 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#5 /var/www/yii-cp/as2/index.php(13): CWebApplication->run()
REQUEST_URI=/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T06%3A04%3A13ZmYXnhnOf6pQ9Wg&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9VmFsgjN2tkF39vP1EwfDNapXPp34_RBjuh1gmVjH2JqmSn1Ln-&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=D2zj0d0bQKujDSpjTrlwSx%2FHk5k%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php (29)
in /var/www/yii-cp/as2/index.php (13)
2012/04/26 08:05:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "success".' in /var/www/yii-cp/framework/web/CController.php:484
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(271): CController->missingAction('success')
#1 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('success')
#2 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/success')
#3 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/success
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T06%3A05%3A20Z1zXN4JJopw9Ydg&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9VuOjNPACd1o7zG9tQciUakBfXI2pBmxvlMn18r5q9biaO0Luul&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=r17%2B0m5xRUmhE59boaOZeroKyLw%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
---
2012/04/26 08:06:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "success".' in /var/www/yii-cp/framework/web/CController.php:484
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(271): CController->missingAction('success')
#1 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('success')
#2 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/success')
#3 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/success
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T06%3A05%3A20Z1zXN4JJopw9Ydg&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9VuOjNPACd1o7zG9tQciUakBfXI2pBmxvlMn18r5q9biaO0Luul&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=r17%2B0m5xRUmhE59boaOZeroKyLw%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
---
2012/04/26 08:06:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "success".' in /var/www/yii-cp/framework/web/CController.php:484
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(271): CController->missingAction('success')
#1 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('success')
#2 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/success')
#3 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/success
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T06%3A05%3A20Z1zXN4JJopw9Ydg&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9VuOjNPACd1o7zG9tQciUakBfXI2pBmxvlMn18r5q9biaO0Luul&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=r17%2B0m5xRUmhE59boaOZeroKyLw%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
---
2012/04/26 08:06:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "success".' in /var/www/yii-cp/framework/web/CController.php:484
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(271): CController->missingAction('success')
#1 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('success')
#2 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/success')
#3 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/success
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T06%3A06%3A15ZjB3hA5PLe3QyKQ&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9WqSudkY5125rGHX3lFZsCt2IUg8XpWYDKA4TMtge6IAlsEM-OL&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=nLfjmnMjyJv2vk%2FHxnbwAEt08kI%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
---
2012/04/26 08:10:12 [error] [exception.EAuthException] exception 'EAuthException' with message 'Unable to complete the authentication because the required data was not received.' in /var/www/yii-cp/as2/protected/extensions/eauth/EOpenIDService.php:77
Stack trace:
#0 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(25): EOpenIDService->authenticate()
#1 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionAuth()
#2 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#3 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#4 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('auth')
#6 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/auth/se...')
#7 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T06%3A09%3A25ZqNOiOn2TTE_3jQ&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9UmQ7xdbJfL2p7M-1RkcAKN4Qbin5lTMOXFyJSiiAjDhcW6McX9&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=tGtG%2BfbNZCzNBUBfY9GyWeSFWMA%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth
---
2012/04/26 08:10:17 [error] [php] Array to string conversion (/var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php:42)
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams()
#1 /var/www/yii-cp/framework/web/CController.php(287): AuthController->runAction()
#2 /var/www/yii-cp/framework/web/CController.php(266): AuthController->runActionWithFilters()
#3 /var/www/yii-cp/framework/web/CWebApplication.php(276): AuthController->run()
#4 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController()
#5 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#6 /var/www/yii-cp/as2/index.php(13): CWebApplication->run()
REQUEST_URI=/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T06%3A10%3A16ZF1e53bG0L0JOSg&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9UKJapFapwk7fRRlWh5rkJe3smQxxnF3OKAnP9mp6KqZOdXjvBO&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=128HGqJ7kvRNbUf2wSNo5%2F93rPQ%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php (42)
in /var/www/yii-cp/as2/index.php (13)
2012/04/26 08:11:26 [error] [php] Array to string conversion (/var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php:45)
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams()
#1 /var/www/yii-cp/framework/web/CController.php(287): AuthController->runAction()
#2 /var/www/yii-cp/framework/web/CController.php(266): AuthController->runActionWithFilters()
#3 /var/www/yii-cp/framework/web/CWebApplication.php(276): AuthController->run()
#4 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController()
#5 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#6 /var/www/yii-cp/as2/index.php(13): CWebApplication->run()
REQUEST_URI=/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T06%3A11%3A24Z7c8RO72Z-MuncA&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9V4PhCecII2BCQkPIRv0CyVSHYs4E-4LbmS80DGsp7-Snl33SK1&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=jjxhZr8tQyKE4q3seQcrpRERx%2B4%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php (45)
in /var/www/yii-cp/as2/index.php (13)
2012/04/26 08:12:04 [error] [php] Array to string conversion (/var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php:44)
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams()
#1 /var/www/yii-cp/framework/web/CController.php(287): AuthController->runAction()
#2 /var/www/yii-cp/framework/web/CController.php(266): AuthController->runActionWithFilters()
#3 /var/www/yii-cp/framework/web/CWebApplication.php(276): AuthController->run()
#4 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController()
#5 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#6 /var/www/yii-cp/as2/index.php(13): CWebApplication->run()
REQUEST_URI=/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T06%3A12%3A02Z8uzBx0PiywcM1Q&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9X3DwGxKF9InpBdHsOUQ_o2DpO5BSMx7iBxDqntuwd0ZjOfa6MR&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=0m6ba9Dl8ixnJAZFnkTGLudF3rA%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php (44)
in /var/www/yii-cp/as2/index.php (13)
2012/04/26 08:12:32 [error] [exception.Exception] exception 'Exception' with message 'Array' in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php:45
Stack trace:
#0 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionAuth()
#1 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#2 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#3 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('auth')
#5 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/auth/se...')
#6 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#7 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T06%3A12%3A30Z7bFid5SEn7DVEw&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9UwamD3T9sJu6z6Q6iYAI28rAXbxOeowmOtZxZvcD5t70RmgGuk&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=k2ZjdW1t3a6Onm0ohLqEt1Ivxz8%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth
---
2012/04/26 08:13:27 [error] [php] Array to string conversion (/var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php:44)
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams()
#1 /var/www/yii-cp/framework/web/CController.php(287): AuthController->runAction()
#2 /var/www/yii-cp/framework/web/CController.php(266): AuthController->runActionWithFilters()
#3 /var/www/yii-cp/framework/web/CWebApplication.php(276): AuthController->run()
#4 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController()
#5 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#6 /var/www/yii-cp/as2/index.php(13): CWebApplication->run()
REQUEST_URI=/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T06%3A13%3A25ZKEVMTxcYVkJg0g&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9VkBzmOqgjrQbd0IYiNfIlF1jrdRQs9FBasRwx-4jrNl0JiTxOy&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=ZIvTi9Fw5C02LRnOerS7JV%2FSL0Y%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php (44)
in /var/www/yii-cp/as2/index.php (13)
2012/04/26 08:14:47 [error] [exception.Exception] exception 'Exception' with message 'Array
(
    [email] => Array
        (
            [0] => Email cannot be blank.
        )

    [salt] => Array
        (
            [0] => Salt cannot be blank.
        )

)
' in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php:44
Stack trace:
#0 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionAuth()
#1 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#2 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#3 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('auth')
#5 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/auth/se...')
#6 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#7 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T06%3A14%3A46Z1tut7Ttk3gNSqg&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9WxJHIst0pjQ-4VeiW_d_XOe0fCxKcn_NllntwOFqfWGjZCnTSj&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=CP7Ir0DLgP9rYvEUH0Rj8YGtWTM%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth
---
2012/04/26 08:15:04 [error] [exception.Exception] exception 'Exception' with message 'Array
(
    [email] => Array
        (
            [0] => Email cannot be blank.
        )

    [salt] => Array
        (
            [0] => Salt cannot be blank.
        )

)
' in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php:44
Stack trace:
#0 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionAuth()
#1 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#2 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#3 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('auth')
#5 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/auth/se...')
#6 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#7 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T06%3A15%3A02ZSsFJ1tU6nHLvHg&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9XgI5sOAkZHV5BQFyu73QwzA2oVO-_Op0HJ4_MLgy4EMmsSOlCF&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=8tZmtSVzPMCx8EbXrK%2FD%2B5VYgRk%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth
---
2012/04/26 08:15:29 [error] [exception.Exception] exception 'Exception' with message 'Array
(
    [email] => Array
        (
            [0] => Email cannot be blank.
        )

)
' in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php:44
Stack trace:
#0 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionAuth()
#1 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#2 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#3 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('auth')
#5 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/auth/se...')
#6 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#7 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T06%3A15%3A28Zn2pmCbx2xpNIEw&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9UlhyYoW7fmyoNg7OxLL1xoIUWlH9KB6myFkpWT7Ygi4DjYEucS&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname&openid.sig=D1J9Ytl%2BkGZQyWO%2FGiL6%2Fv19NJg%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth
---
2012/04/26 08:16:45 [error] [exception.Exception] exception 'Exception' with message 'Array
(
    [id] => Array
        (
            [0] => ID cannot be blank.
        )

)
' in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php:61
Stack trace:
#0 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionAuth()
#1 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#2 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#3 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('auth')
#5 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/auth/se...')
#6 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#7 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T06%3A16%3A43ZodcdNK-ITtnxZw&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9WuuGhktYfHokWjTOR_cBq8XBZ-Qww0EQTB9gQf1ga4f7qiPfaP&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname%2Cext1.type.email%2Cext1.value.email&openid.sig=HhVz7cVXGh5%2FDZEG5x1AUr2Wed0%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.&openid.ext1.type.email=http%3A%2F%2Faxschema.org%2Fcontact%2Femail&openid.ext1.value.email=bram.wall%40gmail.com
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth
---
2012/04/26 08:17:39 [error] [exception.Exception] exception 'Exception' with message 'Array
(
    [key] => Array
        (
            [0] => Key cannot be blank.
        )

)
' in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php:75
Stack trace:
#0 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionAuth()
#1 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#2 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#3 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('auth')
#5 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/auth/se...')
#6 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#7 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T06%3A17%3A37ZLFuZVL8DxxYBIw&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9Xv8OXPPimG_AtaziGi_JxtYisd99BfX1P3zDWDLaIjm8YLunoi&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname%2Cext1.type.email%2Cext1.value.email&openid.sig=vf4b%2FXWhDANiw7CtmnJMUpxl%2Fcg%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.&openid.ext1.type.email=http%3A%2F%2Faxschema.org%2Fcontact%2Femail&openid.ext1.value.email=bram.wall%40gmail.com
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth
---
2012/04/26 08:17:43 [error] [exception.Exception] exception 'Exception' with message 'Array
(
    [key] => Array
        (
            [0] => Key cannot be blank.
        )

)
' in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php:75
Stack trace:
#0 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionAuth()
#1 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#2 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#3 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('auth')
#5 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/auth/se...')
#6 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#7 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T06%3A17%3A42Z5byM_aKMxThi-g&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9UZN7uPHOg3dk9bGI4J78k-P-tXec4XrPYyjxXjY8hkOtb38SGd&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname%2Cext1.type.email%2Cext1.value.email&openid.sig=zGdyf0Q3h%2B0TMI17BzwuAuwQ1HM%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.&openid.ext1.type.email=http%3A%2F%2Faxschema.org%2Fcontact%2Femail&openid.ext1.value.email=bram.wall%40gmail.com
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth
---
2012/04/26 08:18:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "as/aut".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/aut')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/aut
---
2012/04/26 08:18:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "as/aut".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/aut')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/aut
---
2012/04/26 08:18:25 [error] [exception.Exception] exception 'Exception' with message 'Array
(
    [key] => Array
        (
            [0] => Key cannot be blank.
        )

)
' in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php:75
Stack trace:
#0 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionAuth()
#1 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#2 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#3 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('auth')
#5 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/auth/se...')
#6 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#7 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T06%3A18%3A23Zs5bCZrPaMk81Hw&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9UuKWw3OEPgcbhr-rPEXWQa0ZiM8Jw_hB9evHyWRZWPOhRWMfYk&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname%2Cext1.type.email%2Cext1.value.email&openid.sig=4ytmZfxcCuIskW7%2FoOYaEcoHJfg%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.&openid.ext1.type.email=http%3A%2F%2Faxschema.org%2Fcontact%2Femail&openid.ext1.value.email=bram.wall%40gmail.com
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth
---
2012/04/26 08:19:00 [error] [exception.Exception] exception 'Exception' with message 'Array
(
    [key] => Array
        (
            [0] => Key must be an integer.
        )

)
' in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php:75
Stack trace:
#0 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionAuth()
#1 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#2 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#3 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('auth')
#5 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/auth/se...')
#6 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#7 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T06%3A18%3A58ZCCMfqGuIEqj_ag&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9U8d6h4TRHk6LI_DHn_rFRfvsCEvmKDQ_7ftRf0lrarWgw5vw9s&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname%2Cext1.type.email%2Cext1.value.email&openid.sig=IbAzEjoULsE3MXyEzLdqh45Bfok%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.&openid.ext1.type.email=http%3A%2F%2Faxschema.org%2Fcontact%2Femail&openid.ext1.value.email=bram.wall%40gmail.com
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth
---
2012/04/26 08:19:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "success".' in /var/www/yii-cp/framework/web/CController.php:484
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(271): CController->missingAction('success')
#1 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('success')
#2 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/success')
#3 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/success
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T06%3A19%3A14ZYaByNCF1y09kTg&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9W-A2sgl4yBEDJMoL66Iz6cJ0-8yCU7Ex1bKRyzCF74zdj-MAN9&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname%2Cext1.type.email%2Cext1.value.email&openid.sig=Qk2TCDHdE5qrHE7vVY%2FK8d0XXmQ%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.&openid.ext1.type.email=http%3A%2F%2Faxschema.org%2Fcontact%2Femail&openid.ext1.value.email=bram.wall%40gmail.com
---
2012/04/26 08:19:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "success".' in /var/www/yii-cp/framework/web/CController.php:484
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(271): CController->missingAction('success')
#1 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('success')
#2 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/success')
#3 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/success
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T06%3A19%3A27ZqrHWyAvkqtWlFw&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9Xr2-dqGJu10Pizkg5yHlscfiyc1q9qZspBANeezixoUGuT_FTh&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname%2Cext1.type.email%2Cext1.value.email&openid.sig=2bmHSJYESfritOLI%2FmZB3BNGCUM%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.&openid.ext1.type.email=http%3A%2F%2Faxschema.org%2Fcontact%2Femail&openid.ext1.value.email=bram.wall%40gmail.com
---
2012/04/26 16:57:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "success".' in /var/www/yii-cp/framework/web/CController.php:484
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(271): CController->missingAction('success')
#1 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('success')
#2 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/success')
#3 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/success
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-26T06%3A19%3A27ZqrHWyAvkqtWlFw&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9Xr2-dqGJu10Pizkg5yHlscfiyc1q9qZspBANeezixoUGuT_FTh&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname%2Cext1.type.email%2Cext1.value.email&openid.sig=2bmHSJYESfritOLI%2FmZB3BNGCUM%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.&openid.ext1.type.email=http%3A%2F%2Faxschema.org%2Fcontact%2Femail&openid.ext1.value.email=bram.wall%40gmail.com
---
2012/04/26 17:37:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "as/page".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/page')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/page
---
2012/04/26 17:37:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "as/page/index".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/page/index')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/page
---
2012/04/26 17:38:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "page/clan/nl/blaat".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('page/clan/nl/bl...')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/clan/nl/blaat
---
2012/04/26 17:38:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "page/clan/nl/blaat".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('page/clan/nl/bl...')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/clan/nl/blaat
---
2012/04/26 17:40:26 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'alphaserv2.web_pages' doesn't exist. The SQL statement executed was: SHOW COLUMNS FROM `web_pages`.
in /var/www/yii-cp/as2/protected/models/Page.php (24)
in /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php (12)
in /var/www/yii-cp/as2/index.php (13)
2012/04/26 17:40:26 [error] [exception.CDbException] exception 'CDbException' with message 'The table "web_pages" for active record class "Page" cannot be found in the database.' in /var/www/yii-cp/framework/db/ar/CActiveRecord.php:2264
Stack trace:
#0 /var/www/yii-cp/framework/db/ar/CActiveRecord.php(379): CActiveRecordMetaData->__construct(Object(Page))
#1 /var/www/yii-cp/as2/protected/models/Page.php(24): CActiveRecord::model('Page')
#2 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(12): Page::model()
#3 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): PageController->actionIndex()
#4 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#5 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#6 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('')
#8 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/page')
#9 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/clan/nl/blaat
---
2012/04/26 17:44:28 [error] [php] Trying to get property of non-object (/var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php:17)
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(287): PageController->runAction()
#1 /var/www/yii-cp/framework/web/CController.php(266): PageController->runActionWithFilters()
#2 /var/www/yii-cp/framework/web/CWebApplication.php(276): PageController->run()
#3 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController()
#4 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#5 /var/www/yii-cp/as2/index.php(13): CWebApplication->run()
REQUEST_URI=/yii-cp/as2/index.php/page
in /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php (17)
in /var/www/yii-cp/as2/index.php (13)
2012/04/26 17:45:48 [error] [exception.CDbException] exception 'CDbException' with message 'Relation "User" is not defined in active record class "Pages".' in /var/www/yii-cp/framework/db/ar/CActiveFinder.php:215
Stack trace:
#0 /var/www/yii-cp/framework/db/ar/CActiveFinder.php(310): CActiveFinder->buildJoinTree(Object(CJoinElement), 'User')
#1 /var/www/yii-cp/framework/db/ar/CActiveFinder.php(49): CActiveFinder->buildJoinTree(Object(CJoinElement), Array)
#2 /var/www/yii-cp/framework/db/ar/CActiveRecord.php(1291): CActiveFinder->__construct(Object(Pages), Array)
#3 /var/www/yii-cp/framework/db/ar/CActiveRecord.php(1472): CActiveRecord->query(Object(CDbCriteria), true)
#4 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(15): CActiveRecord->findAllByAttributes(Array)
#5 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): PageController->actionIndex()
#6 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#7 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#8 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('')
#10 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/page')
#11 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#12 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii-cp/as2/index.php/page
---
2012/04/26 17:46:27 [error] [exception.CDbException] exception 'CDbException' with message 'Relation "AclObject" is not defined in active record class "Pages".' in /var/www/yii-cp/framework/db/ar/CActiveFinder.php:215
Stack trace:
#0 /var/www/yii-cp/framework/db/ar/CActiveFinder.php(310): CActiveFinder->buildJoinTree(Object(CJoinElement), 'AclObject')
#1 /var/www/yii-cp/framework/db/ar/CActiveFinder.php(49): CActiveFinder->buildJoinTree(Object(CJoinElement), Array)
#2 /var/www/yii-cp/framework/db/ar/CActiveRecord.php(1291): CActiveFinder->__construct(Object(Pages), Array)
#3 /var/www/yii-cp/framework/db/ar/CActiveRecord.php(1472): CActiveRecord->query(Object(CDbCriteria), true)
#4 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(15): CActiveRecord->findAllByAttributes(Array)
#5 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): PageController->actionIndex()
#6 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#7 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#8 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('')
#10 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/page')
#11 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#12 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii-cp/as2/index.php/page
---
2012/04/26 17:46:33 [error] [php] Trying to get property of non-object (/var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php:17)
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(287): PageController->runAction()
#1 /var/www/yii-cp/framework/web/CController.php(266): PageController->runActionWithFilters()
#2 /var/www/yii-cp/framework/web/CWebApplication.php(276): PageController->run()
#3 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController()
#4 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#5 /var/www/yii-cp/as2/index.php(13): CWebApplication->run()
REQUEST_URI=/yii-cp/as2/index.php/page
in /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php (17)
in /var/www/yii-cp/as2/index.php (13)
2012/04/26 17:46:44 [error] [php] Trying to get property of non-object (/var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php:19)
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(287): PageController->runAction()
#1 /var/www/yii-cp/framework/web/CController.php(266): PageController->runActionWithFilters()
#2 /var/www/yii-cp/framework/web/CWebApplication.php(276): PageController->run()
#3 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController()
#4 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#5 /var/www/yii-cp/as2/index.php(13): CWebApplication->run()
REQUEST_URI=/yii-cp/as2/index.php/page
in /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php (19)
in /var/www/yii-cp/as2/index.php (13)
2012/04/26 17:47:08 [error] [php] Trying to get property of non-object (/var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php:19)
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(287): PageController->runAction()
#1 /var/www/yii-cp/framework/web/CController.php(266): PageController->runActionWithFilters()
#2 /var/www/yii-cp/framework/web/CWebApplication.php(276): PageController->run()
#3 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController()
#4 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#5 /var/www/yii-cp/as2/index.php(13): CWebApplication->run()
REQUEST_URI=/yii-cp/as2/index.php/page
in /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php (19)
in /var/www/yii-cp/as2/index.php (13)
2012/04/26 17:48:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "page/about".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('page/about')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/about
---
2012/04/26 17:48:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "page/about".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('page/about')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/about
---
2012/04/26 17:49:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "page/about".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('page/about')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/about
---
2012/04/26 17:49:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "page/about".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('page/about')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/about
---
2012/04/26 17:50:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "page/about".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('page/about')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/about
---
2012/04/26 17:50:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "page/about".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('page/about')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/about
---
2012/04/26 17:50:42 [error] [exception.CException] exception 'CException' with message 'The URL pattern "page/<path:(.*)>\/?" for route "as/page" is not a valid regular expression.' in /var/www/yii-cp/framework/web/CUrlManager.php:700
Stack trace:
#0 /var/www/yii-cp/framework/web/CUrlManager.php(268): CUrlRule->__construct('as/page', 'page/<path:(.*)...')
#1 /var/www/yii-cp/framework/web/CUrlManager.php(227): CUrlManager->createUrlRule('as/page', 'page/<path:(.*)...')
#2 /var/www/yii-cp/framework/web/CUrlManager.php(207): CUrlManager->processRules()
#3 /var/www/yii-cp/framework/base/CModule.php(388): CUrlManager->init()
#4 /var/www/yii-cp/framework/base/CApplication.php(503): CModule->getComponent('urlManager')
#5 /var/www/yii-cp/framework/web/CWebApplication.php(134): CApplication->getUrlManager()
#6 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#7 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/about
---
2012/04/26 17:50:51 [error] [exception.CException] exception 'CException' with message 'The URL pattern "page/<path:(.*)>\/?" for route "as/page" is not a valid regular expression.' in /var/www/yii-cp/framework/web/CUrlManager.php:700
Stack trace:
#0 /var/www/yii-cp/framework/web/CUrlManager.php(268): CUrlRule->__construct('as/page', 'page/<path:(.*)...')
#1 /var/www/yii-cp/framework/web/CUrlManager.php(227): CUrlManager->createUrlRule('as/page', 'page/<path:(.*)...')
#2 /var/www/yii-cp/framework/web/CUrlManager.php(207): CUrlManager->processRules()
#3 /var/www/yii-cp/framework/base/CModule.php(388): CUrlManager->init()
#4 /var/www/yii-cp/framework/base/CApplication.php(503): CModule->getComponent('urlManager')
#5 /var/www/yii-cp/framework/web/CWebApplication.php(134): CApplication->getUrlManager()
#6 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#7 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/about
---
2012/04/26 17:50:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "page/about".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('page/about')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/about
---
2012/04/26 17:51:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "page/about".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('page/about')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/about
---
2012/04/26 17:51:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "page/about".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('page/about')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/about
---
2012/04/26 17:51:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "page/about".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('page/about')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/about
---
2012/04/26 17:51:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "page/about".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('page/about')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/about
---
2012/04/26 17:51:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "page/about".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('page/about')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/about
---
2012/04/26 17:51:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "page/home".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('page/home')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/home
---
2012/04/26 17:52:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "page/home".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('page/home')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/home
---
2012/04/26 17:52:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "page/home".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('page/home')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/home
---
2012/04/26 17:53:30 [error] [exception.CException] exception 'CException' with message 'PageController and its behaviors do not have a method or closure named "transform".' in /var/www/yii-cp/framework/base/CComponent.php:266
Stack trace:
#0 /var/www/yii-cp/framework/utils/CMarkdownParser.php(79): CComponent->__call('transform', Array)
#1 /var/www/yii-cp/framework/utils/CMarkdownParser.php(79): PageController->transform('PAGe page page')
#2 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(29): CMarkdownParser->safeTransform('PAGe page page')
#3 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): PageController->actionIndex()
#4 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#5 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#6 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('')
#8 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/page')
#9 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/
---
2012/04/26 18:35:40 [error] [exception.Exception] exception 'Exception' with message 'Access not found, Could not find user from id' in /var/www/yii-cp/as2/protected/modules/as/components/AccessControl.php:76
Stack trace:
#0 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(29): AccessControl::GetUserAccess(Object(AclObject))
#1 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): PageController->actionIndex()
#2 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#3 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#4 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('')
#6 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/page')
#7 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/
---
2012/04/26 18:35:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "page/home".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('page/home')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/home
---
2012/04/26 18:37:01 [error] [exception.CException] exception 'CException' with message 'Property "User.web_user" is not defined.' in /var/www/yii-cp/framework/base/CComponent.php:131
Stack trace:
#0 /var/www/yii-cp/framework/db/ar/CActiveRecord.php(144): CComponent->__get('web_user')
#1 /var/www/yii-cp/as2/protected/modules/as/components/UserIdentity.php(24): CActiveRecord->__get('web_user')
#2 /var/www/yii-cp/as2/protected/models/LoginForm.php(39): UserIdentity->authenticate()
#3 /var/www/yii-cp/framework/validators/CInlineValidator.php(43): LoginForm->authenticate('password', Array)
#4 /var/www/yii-cp/framework/validators/CValidator.php(197): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 /var/www/yii-cp/framework/base/CModel.php(158): CValidator->validate(Object(LoginForm), NULL)
#6 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(113): CModel->validate()
#7 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(7): AuthController->actionAuth()
#8 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionIndex()
#9 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#10 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#11 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('')
#13 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth')
#14 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#15 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth
---
2012/04/26 18:37:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "page/home".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('page/home')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/home
---
2012/04/26 18:37:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "page/about".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('page/about')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/about
---
2012/04/26 18:37:13 [error] [exception.Exception] exception 'Exception' with message 'Access not found, Could not find user from id' in /var/www/yii-cp/as2/protected/modules/as/components/AccessControl.php:76
Stack trace:
#0 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(29): AccessControl::GetUserAccess(Object(AclObject))
#1 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): PageController->actionIndex()
#2 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#3 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#4 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('')
#6 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/page')
#7 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/
---
2012/04/26 18:38:32 [error] [exception.CException] exception 'CException' with message 'Property "Pages.comments" is not defined.' in /var/www/yii-cp/framework/base/CComponent.php:131
Stack trace:
#0 /var/www/yii-cp/framework/db/ar/CActiveRecord.php(144): CComponent->__get('comments')
#1 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(43): CActiveRecord->__get('comments')
#2 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): PageController->actionIndex()
#3 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#4 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#5 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('')
#7 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/page')
#8 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#9 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/
---
2012/04/26 18:38:57 [error] [exception.CException] exception 'CException' with message 'Property "Pages.update" is not defined.' in /var/www/yii-cp/framework/base/CComponent.php:131
Stack trace:
#0 /var/www/yii-cp/framework/db/ar/CActiveRecord.php(144): CComponent->__get('update')
#1 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(44): CActiveRecord->__get('update')
#2 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): PageController->actionIndex()
#3 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#4 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#5 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('')
#7 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/page')
#8 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#9 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/
---
2012/04/26 18:38:59 [error] [exception.CException] exception 'CException' with message 'Property "Pages.update" is not defined.' in /var/www/yii-cp/framework/base/CComponent.php:131
Stack trace:
#0 /var/www/yii-cp/framework/db/ar/CActiveRecord.php(144): CComponent->__get('update')
#1 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(44): CActiveRecord->__get('update')
#2 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): PageController->actionIndex()
#3 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#4 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#5 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('')
#7 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/page')
#8 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#9 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/
---
2012/04/26 18:42:55 [error] [exception.CException] exception 'CException' with message 'Property "User.name" is not defined.' in /var/www/yii-cp/framework/base/CComponent.php:131
Stack trace:
#0 /var/www/yii-cp/framework/db/ar/CActiveRecord.php(144): CComponent->__get('name')
#1 /var/www/yii-cp/as2/protected/modules/as/views/page/page.php(11): CActiveRecord->__get('name')
#2 /var/www/yii-cp/framework/web/CBaseController.php(127): require('/var/www/yii-cp...')
#3 /var/www/yii-cp/framework/web/CBaseController.php(96): CBaseController->renderInternal('/var/www/yii-cp...', Array, true)
#4 /var/www/yii-cp/framework/web/CController.php(870): CBaseController->renderFile('/var/www/yii-cp...', Array, true)
#5 /var/www/yii-cp/framework/web/CController.php(783): CController->renderPartial('page', Array, true)
#6 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(49): CController->render('page', Array)
#7 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): PageController->actionIndex()
#8 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#9 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#10 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('')
#12 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/page')
#13 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#14 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/
---
2012/04/26 18:46:24 [error] [exception.CException] exception 'CException' with message 'Property "User.profile" is not defined.' in /var/www/yii-cp/framework/base/CComponent.php:131
Stack trace:
#0 /var/www/yii-cp/framework/db/ar/CActiveRecord.php(144): CComponent->__get('profile')
#1 /var/www/yii-cp/as2/protected/modules/as/views/page/page.php(14): CActiveRecord->__get('profile')
#2 /var/www/yii-cp/framework/web/CBaseController.php(127): require('/var/www/yii-cp...')
#3 /var/www/yii-cp/framework/web/CBaseController.php(96): CBaseController->renderInternal('/var/www/yii-cp...', Array, true)
#4 /var/www/yii-cp/framework/web/CController.php(870): CBaseController->renderFile('/var/www/yii-cp...', Array, true)
#5 /var/www/yii-cp/framework/web/CController.php(783): CController->renderPartial('page', Array, true)
#6 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(49): CController->render('page', Array)
#7 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): PageController->actionIndex()
#8 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#9 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#10 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('')
#12 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/page')
#13 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#14 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/
---
2012/04/26 19:02:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "as/profile/view/id/2".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/profile/view...')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/profile/view/id/2
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/page/
---
2012/04/26 19:15:23 [error] [php] Division by zero (/var/www/yii-cp/as2/protected/modules/as/views/page/page.php:52)
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(870): PageController->renderFile()
#1 /var/www/yii-cp/framework/web/CController.php(783): PageController->renderPartial()
#2 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(49): PageController->render()
#3 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): PageController->actionIndex()
#4 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams()
#5 /var/www/yii-cp/framework/web/CController.php(287): PageController->runAction()
#6 /var/www/yii-cp/framework/web/CController.php(266): PageController->runActionWithFilters()
#7 /var/www/yii-cp/framework/web/CWebApplication.php(276): PageController->run()
#8 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController()
#9 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/yii-cp/as2/index.php(13): CWebApplication->run()
REQUEST_URI=/yii-cp/as2/index.php/page/
in /var/www/yii-cp/as2/protected/modules/as/views/page/page.php (52)
in /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php (49)
in /var/www/yii-cp/as2/index.php (13)
2012/04/26 20:54:00 [error] [php] Undefined offset: -11 (/var/www/yii-cp/as2/protected/modules/as/views/page/page.php:65)
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(870): PageController->renderFile()
#1 /var/www/yii-cp/framework/web/CController.php(783): PageController->renderPartial()
#2 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(49): PageController->render()
#3 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): PageController->actionIndex()
#4 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams()
#5 /var/www/yii-cp/framework/web/CController.php(287): PageController->runAction()
#6 /var/www/yii-cp/framework/web/CController.php(266): PageController->runActionWithFilters()
#7 /var/www/yii-cp/framework/web/CWebApplication.php(276): PageController->run()
#8 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController()
#9 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/yii-cp/as2/index.php(13): CWebApplication->run()
REQUEST_URI=/yii-cp/as2/index.php/page/
in /var/www/yii-cp/as2/protected/modules/as/views/page/page.php (65)
in /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php (49)
in /var/www/yii-cp/as2/index.php (13)
2012/04/26 20:54:15 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Page not found.' in /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php:27
Stack trace:
#0 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): PageController->actionIndex()
#1 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#2 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#3 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('')
#5 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/page')
#6 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#7 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/page/id/.../reaction/.../action/vote/add/1
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/page/
---
2012/04/26 21:00:27 [error] [php] Undefined offset: -11 (/var/www/yii-cp/as2/protected/modules/as/views/page/page.php:75)
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(870): PageController->renderFile()
#1 /var/www/yii-cp/framework/web/CController.php(783): PageController->renderPartial()
#2 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(50): PageController->render()
#3 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): PageController->actionIndex()
#4 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams()
#5 /var/www/yii-cp/framework/web/CController.php(287): PageController->runAction()
#6 /var/www/yii-cp/framework/web/CController.php(266): PageController->runActionWithFilters()
#7 /var/www/yii-cp/framework/web/CWebApplication.php(276): PageController->run()
#8 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController()
#9 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/yii-cp/as2/index.php(13): CWebApplication->run()
REQUEST_URI=/yii-cp/as2/index.php/page/
in /var/www/yii-cp/as2/protected/modules/as/views/page/page.php (75)
in /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php (50)
in /var/www/yii-cp/as2/index.php (13)
2012/04/26 21:06:17 [error] [exception.CException] exception 'CException' with message 'CHttpRequest and its behaviors do not have a method or closure named "getQuert".' in /var/www/yii-cp/framework/base/CComponent.php:266
Stack trace:
#0 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(68): CComponent->__call('getQuert', Array)
#1 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(68): CHttpRequest->getQuert('add')
#2 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): PageController->actionAction()
#3 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#4 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#5 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('action')
#7 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/page/action/...')
#8 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#9 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/page/action/id/1/reaction/1/action/vote/sub/1
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/page/
---
2012/04/26 21:08:01 [error] [exception.CException] exception 'CException' with message 'CHttpRequest and its behaviors do not have a method or closure named "getQuert".' in /var/www/yii-cp/framework/base/CComponent.php:266
Stack trace:
#0 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(65): CComponent->__call('getQuert', Array)
#1 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(65): CHttpRequest->getQuert('add')
#2 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): PageController->actionAction()
#3 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#4 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#5 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('action')
#7 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/page/action/...')
#8 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#9 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/page/action/id/1/reaction/1/action/vote/sub/1
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/page/
---
2012/04/26 21:11:18 [error] [php] Undefined variable: action (/var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php:60)
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(287): PageController->runAction()
#1 /var/www/yii-cp/framework/web/CController.php(266): PageController->runActionWithFilters()
#2 /var/www/yii-cp/framework/web/CWebApplication.php(276): PageController->run()
#3 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController()
#4 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#5 /var/www/yii-cp/as2/index.php(13): CWebApplication->run()
REQUEST_URI=/yii-cp/as2/index.php/as/page/action/id/1/reaction/1/action/vote/sub/1
in /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php (60)
in /var/www/yii-cp/as2/index.php (13)
2012/04/26 21:11:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "page/about".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('page/about')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/about
---
2012/04/26 21:57:07 [error] [exception.Exception] exception 'Exception' with message 'Array
(
    [user_id] => Array
        (
            [0] => User cannot be blank.
        )

)
' in /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php:75
Stack trace:
#0 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): PageController->actionAction()
#1 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#2 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#3 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('action')
#5 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/page/action/...')
#6 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#7 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/page/action/id/1/reaction/1/action/vote/sub/1
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/page/
---
2012/04/26 21:57:49 [error] [exception.CException] exception 'CException' with message 'User and its behaviors do not have a method or closure named "GetByPk".' in /var/www/yii-cp/framework/base/CComponent.php:266
Stack trace:
#0 /var/www/yii-cp/framework/db/ar/CActiveRecord.php(226): CComponent->__call('GetByPk', Array)
#1 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(71): CActiveRecord->__call('GetByPk', Array)
#2 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(71): User->GetByPk(NULL)
#3 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): PageController->actionAction()
#4 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#5 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#6 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('action')
#8 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/page/action/...')
#9 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/page/action/id/1/reaction/1/action/vote/sub/1
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/page/
---
2012/04/26 21:58:00 [error] [exception.CException] exception 'CException' with message 'User and its behaviors do not have a method or closure named "GetByPK".' in /var/www/yii-cp/framework/base/CComponent.php:266
Stack trace:
#0 /var/www/yii-cp/framework/db/ar/CActiveRecord.php(226): CComponent->__call('GetByPK', Array)
#1 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(71): CActiveRecord->__call('GetByPK', Array)
#2 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(71): User->GetByPK(NULL)
#3 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): PageController->actionAction()
#4 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#5 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#6 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('action')
#8 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/page/action/...')
#9 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/page/action/id/1/reaction/1/action/vote/sub/1
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/page/
---
2012/04/26 21:58:00 [error] [exception.CException] exception 'CException' with message 'User and its behaviors do not have a method or closure named "GetByPK".' in /var/www/yii-cp/framework/base/CComponent.php:266
Stack trace:
#0 /var/www/yii-cp/framework/db/ar/CActiveRecord.php(226): CComponent->__call('GetByPK', Array)
#1 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(71): CActiveRecord->__call('GetByPK', Array)
#2 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(71): User->GetByPK(NULL)
#3 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): PageController->actionAction()
#4 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#5 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#6 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('action')
#8 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/page/action/...')
#9 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/page/action/id/1/reaction/1/action/vote/sub/1
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/page/
---
2012/04/26 21:58:38 [error] [exception.Exception] exception 'Exception' with message 'Array
(
    [user_id] => Array
        (
            [0] => User cannot be blank.
        )

)
' in /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php:75
Stack trace:
#0 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): PageController->actionAction()
#1 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#2 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#3 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('action')
#5 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/page/action/...')
#6 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#7 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/page/action/id/1/reaction/1/action/vote/sub/1
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/page/
---
2012/04/26 22:00:17 [error] [exception.CException] exception 'CException' with message 'Property "User.web_user" is not defined.' in /var/www/yii-cp/framework/base/CComponent.php:131
Stack trace:
#0 /var/www/yii-cp/framework/db/ar/CActiveRecord.php(144): CComponent->__get('web_user')
#1 /var/www/yii-cp/as2/protected/modules/as/components/UserIdentity.php(24): CActiveRecord->__get('web_user')
#2 /var/www/yii-cp/as2/protected/models/LoginForm.php(39): UserIdentity->authenticate()
#3 /var/www/yii-cp/framework/validators/CInlineValidator.php(43): LoginForm->authenticate('password', Array)
#4 /var/www/yii-cp/framework/validators/CValidator.php(197): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 /var/www/yii-cp/framework/base/CModel.php(158): CValidator->validate(Object(LoginForm), NULL)
#6 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(113): CModel->validate()
#7 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(7): AuthController->actionAuth()
#8 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionIndex()
#9 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#10 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#11 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('')
#13 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth')
#14 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#15 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth
---
2012/04/26 22:01:39 [error] [exception.CException] exception 'CException' with message 'Property "User.hash_method" is not defined.' in /var/www/yii-cp/framework/base/CComponent.php:131
Stack trace:
#0 /var/www/yii-cp/framework/db/ar/CActiveRecord.php(144): CComponent->__get('hash_method')
#1 /var/www/yii-cp/as2/protected/modules/as/components/UserIdentity.php(24): CActiveRecord->__get('hash_method')
#2 /var/www/yii-cp/as2/protected/models/LoginForm.php(39): UserIdentity->authenticate()
#3 /var/www/yii-cp/framework/validators/CInlineValidator.php(43): LoginForm->authenticate('password', Array)
#4 /var/www/yii-cp/framework/validators/CValidator.php(197): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 /var/www/yii-cp/framework/base/CModel.php(158): CValidator->validate(Object(LoginForm), NULL)
#6 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(113): CModel->validate()
#7 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(7): AuthController->actionAuth()
#8 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionIndex()
#9 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#10 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#11 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('')
#13 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth')
#14 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#15 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth
---
2012/04/26 22:01:52 [error] [exception.CException] exception 'CException' with message 'Property "User.hashMethod" is not defined.' in /var/www/yii-cp/framework/base/CComponent.php:131
Stack trace:
#0 /var/www/yii-cp/framework/db/ar/CActiveRecord.php(144): CComponent->__get('hashMethod')
#1 /var/www/yii-cp/as2/protected/modules/as/components/UserIdentity.php(24): CActiveRecord->__get('hashMethod')
#2 /var/www/yii-cp/as2/protected/models/LoginForm.php(39): UserIdentity->authenticate()
#3 /var/www/yii-cp/framework/validators/CInlineValidator.php(43): LoginForm->authenticate('password', Array)
#4 /var/www/yii-cp/framework/validators/CValidator.php(197): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 /var/www/yii-cp/framework/base/CModel.php(158): CValidator->validate(Object(LoginForm), NULL)
#6 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(113): CModel->validate()
#7 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(7): AuthController->actionAuth()
#8 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionIndex()
#9 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#10 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#11 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('')
#13 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth')
#14 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#15 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth
---
2012/04/26 22:02:11 [error] [php] Undefined variable: web_user (/var/www/yii-cp/as2/protected/modules/as/components/UserIdentity.php:27)
Stack trace:
#0 /var/www/yii-cp/framework/validators/CValidator.php(197): CInlineValidator->validateAttribute()
#1 /var/www/yii-cp/framework/base/CModel.php(158): CInlineValidator->validate()
#2 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(113): LoginForm->validate()
#3 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(7): AuthController->actionAuth()
#4 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionIndex()
#5 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams()
#6 /var/www/yii-cp/framework/web/CController.php(287): AuthController->runAction()
#7 /var/www/yii-cp/framework/web/CController.php(266): AuthController->runActionWithFilters()
#8 /var/www/yii-cp/framework/web/CWebApplication.php(276): AuthController->run()
#9 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController()
#10 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#11 /var/www/yii-cp/as2/index.php(13): CWebApplication->run()
REQUEST_URI=/yii-cp/as2/index.php/as/auth
in /var/www/yii-cp/as2/protected/modules/as/components/UserIdentity.php (27)
in /var/www/yii-cp/as2/protected/models/LoginForm.php (39)
in /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php (113)
2012/04/26 22:02:37 [error] [exception.CException] exception 'CException' with message 'Property "User.name" is not defined.' in /var/www/yii-cp/framework/base/CComponent.php:131
Stack trace:
#0 /var/www/yii-cp/framework/db/ar/CActiveRecord.php(144): CComponent->__get('name')
#1 /var/www/yii-cp/as2/protected/modules/as/components/UserIdentity.php(41): CActiveRecord->__get('name')
#2 /var/www/yii-cp/as2/protected/models/LoginForm.php(39): UserIdentity->authenticate()
#3 /var/www/yii-cp/framework/validators/CInlineValidator.php(43): LoginForm->authenticate('password', Array)
#4 /var/www/yii-cp/framework/validators/CValidator.php(197): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 /var/www/yii-cp/framework/base/CModel.php(158): CValidator->validate(Object(LoginForm), NULL)
#6 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(113): CModel->validate()
#7 /var/www/yii-cp/as2/protected/modules/as/controllers/AuthController.php(7): AuthController->actionAuth()
#8 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): AuthController->actionIndex()
#9 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#10 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#11 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('')
#13 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth')
#14 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#15 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth
---
2012/04/26 22:02:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "page/about".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('page/about')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/about
---
2012/04/26 22:03:37 [error] [php] array_count_values() [<a href='function.array-count-values'>function.array-count-values</a>]: Can only count STRING and INTEGER values! (/var/www/yii-cp/as2/protected/modules/as/views/page/page.php:58)
Stack trace:
#0 /var/www/yii-cp/framework/web/CBaseController.php(96): PageController->renderInternal()
#1 /var/www/yii-cp/framework/web/CController.php(870): PageController->renderFile()
#2 /var/www/yii-cp/framework/web/CController.php(783): PageController->renderPartial()
#3 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(50): PageController->render()
#4 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): PageController->actionIndex()
#5 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams()
#6 /var/www/yii-cp/framework/web/CController.php(287): PageController->runAction()
#7 /var/www/yii-cp/framework/web/CController.php(266): PageController->runActionWithFilters()
#8 /var/www/yii-cp/framework/web/CWebApplication.php(276): PageController->run()
#9 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController()
#10 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#11 /var/www/yii-cp/as2/index.php(13): CWebApplication->run()
REQUEST_URI=/yii-cp/as2/index.php/page/
in /var/www/yii-cp/as2/protected/modules/as/views/page/page.php (58)
in /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php (50)
in /var/www/yii-cp/as2/index.php (13)
2012/04/26 22:03:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "page/about".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('page/about')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/about
---
2012/04/26 22:03:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "page/about".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('page/about')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/page/about
---
2012/04/26 22:03:44 [error] [php] array_count_values() [<a href='function.array-count-values'>function.array-count-values</a>]: Can only count STRING and INTEGER values! (/var/www/yii-cp/as2/protected/modules/as/views/page/page.php:58)
Stack trace:
#0 /var/www/yii-cp/framework/web/CBaseController.php(96): PageController->renderInternal()
#1 /var/www/yii-cp/framework/web/CController.php(870): PageController->renderFile()
#2 /var/www/yii-cp/framework/web/CController.php(783): PageController->renderPartial()
#3 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(50): PageController->render()
#4 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): PageController->actionIndex()
#5 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams()
#6 /var/www/yii-cp/framework/web/CController.php(287): PageController->runAction()
#7 /var/www/yii-cp/framework/web/CController.php(266): PageController->runActionWithFilters()
#8 /var/www/yii-cp/framework/web/CWebApplication.php(276): PageController->run()
#9 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController()
#10 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#11 /var/www/yii-cp/as2/index.php(13): CWebApplication->run()
REQUEST_URI=/yii-cp/as2/index.php/page/
in /var/www/yii-cp/as2/protected/modules/as/views/page/page.php (58)
in /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php (50)
in /var/www/yii-cp/as2/index.php (13)
2012/04/26 22:08:19 [error] [exception.CException] exception 'CException' with message 'CommentVotes and its behaviors do not have a method or closure named "getAllByAttributes".' in /var/www/yii-cp/framework/base/CComponent.php:266
Stack trace:
#0 /var/www/yii-cp/framework/db/ar/CActiveRecord.php(226): CComponent->__call('getAllByAttribu...', Array)
#1 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(69): CActiveRecord->__call('getAllByAttribu...', Array)
#2 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(69): CommentVotes->getAllByAttributes(Array)
#3 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): PageController->actionAction()
#4 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#5 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#6 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('action')
#8 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/page/action/...')
#9 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/page/action/id/1/reaction/1/action/vote/sub/1
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/page/
---
2012/04/26 22:08:29 [error] [exception.CException] exception 'CException' with message 'CommentVotes and its behaviors do not have a method or closure named "getAllByAttribute".' in /var/www/yii-cp/framework/base/CComponent.php:266
Stack trace:
#0 /var/www/yii-cp/framework/db/ar/CActiveRecord.php(226): CComponent->__call('getAllByAttribu...', Array)
#1 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(69): CActiveRecord->__call('getAllByAttribu...', Array)
#2 /var/www/yii-cp/as2/protected/modules/as/controllers/PageController.php(69): CommentVotes->getAllByAttribute(Array)
#3 /var/www/yii-cp/framework/web/actions/CInlineAction.php(50): PageController->actionAction()
#4 /var/www/yii-cp/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#5 /var/www/yii-cp/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#6 /var/www/yii-cp/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('action')
#8 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/page/action/...')
#9 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/page/action/id/1/reaction/1/action/vote/sub/1
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/page/
---
2012/04/27 14:43:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "success".' in /var/www/yii-cp/framework/web/CController.php:484
Stack trace:
#0 /var/www/yii-cp/framework/web/CController.php(271): CController->missingAction('success')
#1 /var/www/yii-cp/framework/web/CWebApplication.php(276): CController->run('success')
#2 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/auth/success')
#3 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/auth/success
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth/auth/service/google?redirect_uri=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle&js&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2012-04-27T12%3A43%3A49Z9r-hNco9Zakgpw&openid.return_to=http%3A%2F%2Flocalhost%2Fyii-cp%2Fas2%2Findex.php%2Fas%2Fauth%2Fauth%2Fservice%2Fgoogle%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%252Fyii-cp%252Fas2%252Findex.php%252Fas%252Fauth%252Fauth%252Fservice%252Fgoogle%26js&openid.assoc_handle=AMlYA9VS54mwIQJ521uCCOcwjoQFuOOXhVhC3K1_NrzsSEZdwM7w0kfp&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.firstname%2Cext1.value.firstname%2Cext1.type.email%2Cext1.value.email&openid.sig=vX8Z91NAM3%2FyEEBy7KvfMY110PE%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawlnQUy6nUnh155_25jMLB0pLRp9oa6kthk&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.firstname=b.&openid.ext1.type.email=http%3A%2F%2Faxschema.org%2Fcontact%2Femail&openid.ext1.value.email=bram.wall%40gmail.com
---
2012/04/27 14:56:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "as/as/auth/login".' in /var/www/yii-cp/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii-cp/framework/web/CWebApplication.php(135): CWebApplication->runController('as/as/auth/logi...')
#1 /var/www/yii-cp/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/yii-cp/as2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-cp/as2/index.php/as/as/auth/login
HTTP_REFERER=http://localhost/yii-cp/as2/index.php/as/auth
---
